from typing import Callable, Collection
import ioc
import pandas as pd
from pytest_bdd import given, scenarios, when, then, parsers
from unittest.mock import Mock, patch

import sys, os
sys.path.append(os.path.join(sys.path[0] + '/../../'))

from src.dfsm.initiators import rules_providing, validators_providing
from src.dfsm.state_maps import DefaultStateMap
from src.dfsm.interfaces import StateInterface, BranchStateInterface


def get_next_idx_from_table(table: pd.DataFrame, current_idx: int):
    return table.loc[current_idx, 'NEXT'].item()


def get_follow_symbols_from_table(table: pd.DataFrame, current_idx: int):
    return table.loc[current_idx, 'FOLLOW_SYMBOLS'].item()


def get_state_vector(table: pd.DataFrame, current_idx: int):
    return table.loc[current_idx, ['ACCEPT','STACK','ERROR','RETURN']].tolist()


@given(
    parsers.cfparse(
        'given navigation table by {table_path}.',
        extra_types={"table_path": str}
    ),
    target_fixture='navigation_table'
)
def getting_table(table_path):
    table = pd.read_csv(table_path, index_col=0)
    return table



@given(
    'states map generated by this table.',
    target_fixture='states_map'
)
def generating_states_map(navigation_table):
    ...
